### ISSUE TITLE
re: simple-voice-chat for non-premium accounts

### ISSUE THREAD

**Issue by brawaru** [Brawaru/public-comms#2]
CC: @yebanme @T3g4nTheCoder 

I'm not sure you will be able to see these pings, but I don't want to share this in original issue, because I know that many developers are against any form of piracy, even when sometimes you might have a reason for that (I personally wasn't been able to afford Minecraft for many years until this new year, and I know that some my friends still can't).

I would suggest you guys use some service like Ely.by and AuthLib injector (which basically replaces Minecraft built-in authentication library with a custom one). You need it on both all connecting game clients and on the server itself. But it's as easy as downloading a file and adding an argument like `-Xmx..`. Here's more info:  https://docs.ely.by/en/authlib-injector.html

This way you'll be able to keep `online-mode=true` but still enjoy the game, being able to use all mods, plugins and having a skin. For your friends that don't have Minecraft premium to use Minecraft Launcher, they can use the **original** [TL launcher](https://www.facebook.com/TL-331216497379662/) (not ‘TLauncher’ in Google, which is a stolen adware copycat). TL supports Ely.by out of the box, you can find it in multiple forms: [Installer](https://tlaun.ch/installer), [JAR](https://tlaun.ch/jar), [as a standalone Windows executable](https://tlaun.ch/latest/exe).

Hope that helps?

**Comment by yebanme** [comment]
Thank you for sharing. I am in the same situation as you. I purchased Minecraft, but some of my friends are temporarily unable to purchase Minecraft. I will try the method you mentioned later, anyway thank you very much

**Comment by iT3g4n** [comment]
Yes I did see the ping. Thank you very much for sharing this information :)

**Comment by iT3g4n** [comment]
Oh, @Brawaru, is there a way to use Mojang AND ely.by's auth servers together? Because it's a pain to get people with premium to do this.

**Comment by brawaru** [comment]
> @T3g4nTheCoder:
>
> is there a way to use Mojang AND ely.by's auth servers together

I managed to do this on my very server back in the days but the other way (not with authlib injector, but rather now illegal Java reflection :D), but unfortunately, I don't think it's a good idea for multiple reasons:
- When using Mojang authentication library on the client (e.g. playing through official launcher), it checks all skin signatures against the whitelist of CDN domains. If server sends such client a Ely.by skin signature, the client will reject it (because it doesn't come from allowed domain) and print ‘Tampered’ warning message in the console, so all Ely.by players will be skinless (or rather, steveful? ![Minecraft Steve face](https://user-images.githubusercontent.com/10401817/126170135-cbb7046b-4152-42ef-9367-d1f3ca4a57a5.png)).
- UUID conflicts: Ely.by and Mojang use different UUIDs for users and they might collide (this is extremely rare, but still possible and consequences are unknown), you can make your authentication server that assigns your own unique UUIDs to users and keeps track of which authentication server is originally used, but that requires a database, publicly accessible HTTP server, etc; and doesn't fix the ‘tampered’ problem.

So I think sticking to one authentication solution will be a much better choice.. kinda can think of it as a price to pay for piracy? Giving it's not _that_ inconvenient with tools like TL (thankfully)

![Cartoon shrug](https://user-images.githubusercontent.com/10401817/126169020-6d4f03b4-2e36-418a-883e-98577e511a2b.png)

**Comment by iT3g4n** [comment]
Ah ok, Thank you so much for helping me with this. At the moment I just have DiscordSRV for proximity chat, so I'll try and find another way to do this.

Someone can close this thread if they want idk why it's still open tbh.

@Brawaru :)

**Comment by brawaru** [comment]
👍🏻
